~/share/usr/bin/bigWigToBedGraph ./bigwig_files/BC_DRIP_WT_GSE117671.bw BC_DRIP_WT_GSE117671.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/CHLA10_DRIP_WT_GSE68847.bw CHLA10_DRIP_WT_GSE68847.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/GSM3681019_Rep1_RRChIP_neg.bw GSM3681019_Rep1_RRChIP_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/GSM3681019_Rep1_RRChIP_pos.bw GSM3681019_Rep1_RRChIP_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/GSM3681020_Rep2_RRChIP_neg.bw GSM3681020_Rep2_RRChIP_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/GSM3681020_Rep2_RRChIP_pos.bw GSM3681020_Rep2_RRChIP_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/GSM4474217_NC.bw GSM4474217_NC.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_DRB0_GSE97072_neg.bw HEK293_RCHIP_DRB0_GSE97072_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_DRB0_GSE97072_pos.bw HEK293_RCHIP_DRB0_GSE97072_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_DRB30_GSE97072_neg.bw HEK293_RCHIP_DRB30_GSE97072_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_DRB30_GSE97072_pos.bw HEK293_RCHIP_DRB30_GSE97072_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_DRBwash30_GSE97072_neg.bw HEK293_RCHIP_DRBwash30_GSE97072_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_DRBwash30_GSE97072_pos.bw HEK293_RCHIP_DRBwash30_GSE97072_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_Input_GSE97072_neg.bw HEK293_RCHIP_Input_GSE97072_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_Input_GSE97072_pos.bw HEK293_RCHIP_Input_GSE97072_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WKKD_GSE97072_neg.bw HEK293_RCHIP_WKKD_GSE97072_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WKKD_GSE97072_pos.bw HEK293_RCHIP_WKKD_GSE97072_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WT_GSE97072_rep1_neg.bw HEK293_RCHIP_WT_GSE97072_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WT_GSE97072_rep1_pos.bw HEK293_RCHIP_WT_GSE97072_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WT_GSE97072_rep2_neg.bw HEK293_RCHIP_WT_GSE97072_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WT_GSE97072_rep2_pos.bw HEK293_RCHIP_WT_GSE97072_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WT_GSE97072_rep3_neg.bw HEK293_RCHIP_WT_GSE97072_rep3_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RCHIP_WT_GSE97072_rep3_pos.bw HEK293_RCHIP_WT_GSE97072_rep3_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RDIP_INPUT_GSE68953_neg.bw HEK293_RDIP_INPUT_GSE68953_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RDIP_INPUT_GSE68953_pos.bw HEK293_RDIP_INPUT_GSE68953_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RDIP_WT_GSE68953_neg.bw HEK293_RDIP_WT_GSE68953_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HEK293_RDIP_WT_GSE68953_pos.bw HEK293_RDIP_WT_GSE68953_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_INPUT_GSE93368_rep1.bw HeLa_DRIP_INPUT_GSE93368_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_INPUT_GSE93368_rep2.bw HeLa_DRIP_INPUT_GSE93368_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_INPUT_Pasero0520_rep1.bw HeLa_DRIP_INPUT_Pasero0520_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_INPUT_Pasero0520_rep2.bw HeLa_DRIP_INPUT_Pasero0520_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_RNaseH_LS2C.bw HeLa_DRIP_RNaseH_LS2C.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_WT_GSE93368_rep1.bw HeLa_DRIP_WT_GSE93368_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_WT_GSE93368_rep2.bw HeLa_DRIP_WT_GSE93368_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_WT_LS2A_rep1.bw HeLa_DRIP_WT_LS2A_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_WT_LS2B_rep2.bw HeLa_DRIP_WT_LS2B_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_WT_Pasero0520_rep1.bw HeLa_DRIP_WT_Pasero0520_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIP_WT_Pasero0520_rep2.bw HeLa_DRIP_WT_Pasero0520_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIPc_WT_LS61A_rep1_neg.bw HeLa_DRIPc_WT_LS61A_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIPc_WT_LS61A_rep1_pos.bw HeLa_DRIPc_WT_LS61A_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIPc_WT_LS61C_rep2_neg.bw HeLa_DRIPc_WT_LS61C_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIPc_WT_LS61C_rep2_pos.bw HeLa_DRIPc_WT_LS61C_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIPc_WT_LS61H_rep3_neg.bw HeLa_DRIPc_WT_LS61H_rep3_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_DRIPc_WT_LS61H_rep3_pos.bw HeLa_DRIPc_WT_LS61H_rep3_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_WKKD_GSE87607_neg.bw HeLa_RCHIP_WKKD_GSE87607_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_WKKD_GSE87607_pos.bw HeLa_RCHIP_WKKD_GSE87607_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_WT_GSE87607_rep1_neg.bw HeLa_RCHIP_WT_GSE87607_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_WT_GSE87607_rep1_pos.bw HeLa_RCHIP_WT_GSE87607_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_WT_GSE87607_rep2_neg.bw HeLa_RCHIP_WT_GSE87607_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_WT_GSE87607_rep2_pos.bw HeLa_RCHIP_WT_GSE87607_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_pRNH1_GSE87607_rep1_neg.bw HeLa_RCHIP_pRNH1_GSE87607_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_pRNH1_GSE87607_rep1_pos.bw HeLa_RCHIP_pRNH1_GSE87607_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_pRNH1_GSE87607_rep2_neg.bw HeLa_RCHIP_pRNH1_GSE87607_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RCHIP_pRNH1_GSE87607_rep2_pos.bw HeLa_RCHIP_pRNH1_GSE87607_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RDIP_WT_GSE120371_rep1_neg.bw HeLa_RDIP_WT_GSE120371_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RDIP_WT_GSE120371_rep1_pos.bw HeLa_RDIP_WT_GSE120371_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RDIP_WT_GSE120371_rep2_neg.bw HeLa_RDIP_WT_GSE120371_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_RDIP_WT_GSE120371_rep2_pos.bw HeLa_RDIP_WT_GSE120371_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_INPUT_rep1_neg.bw HeLa_qDRIP_INPUT_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_INPUT_rep1_pos.bw HeLa_qDRIP_INPUT_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_INPUT_rep3_neg.bw HeLa_qDRIP_INPUT_rep3_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_INPUT_rep3_pos.bw HeLa_qDRIP_INPUT_rep3_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_INPUT_rep4_neg.bw HeLa_qDRIP_INPUT_rep4_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_INPUT_rep4_pos.bw HeLa_qDRIP_INPUT_rep4_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_RNaseH_neg.bw HeLa_qDRIP_RNaseH_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_RNaseH_pos.bw HeLa_qDRIP_RNaseH_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep1_neg.bw HeLa_qDRIP_WT_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep1_pos.bw HeLa_qDRIP_WT_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep2_neg.bw HeLa_qDRIP_WT_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep2_pos.bw HeLa_qDRIP_WT_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep3_neg.bw HeLa_qDRIP_WT_rep3_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep3_pos.bw HeLa_qDRIP_WT_rep3_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep4_neg.bw HeLa_qDRIP_WT_rep4_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_qDRIP_WT_rep4_pos.bw HeLa_qDRIP_WT_rep4_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_ssDRIP_WT_GSE134964_rep1_neg.bw HeLa_ssDRIP_WT_GSE134964_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_ssDRIP_WT_GSE134964_rep1_pos.bw HeLa_ssDRIP_WT_GSE134964_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_ssDRIP_WT_GSE134964_rep2_neg.bw HeLa_ssDRIP_WT_GSE134964_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_ssDRIP_WT_GSE134964_rep2_pos.bw HeLa_ssDRIP_WT_GSE134964_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_ssDRIP_WT_GSE134964_rep3_neg.bw HeLa_ssDRIP_WT_GSE134964_rep3_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/HeLa_ssDRIP_WT_GSE134964_rep3_pos.bw HeLa_ssDRIP_WT_GSE134964_rep3_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/IMR90_RDIP_INPUT_GSE68953_neg.bw IMR90_RDIP_INPUT_GSE68953_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/IMR90_RDIP_INPUT_GSE68953_pos.bw IMR90_RDIP_INPUT_GSE68953_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/IMR90_RDIP_WT_GSE68953_neg.bw IMR90_RDIP_WT_GSE68953_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/IMR90_RDIP_WT_GSE68953_pos.bw IMR90_RDIP_WT_GSE68953_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIP_RNaseH_GSE127979.bw K562_DRIP_RNaseH_GSE127979.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIP_WT_GSE127979.bw K562_DRIP_WT_GSE127979.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIP_WT_LS42C.bw K562_DRIP_WT_LS42C.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_RNaseH_GSE127979_neg.bw K562_DRIPc_RNaseH_GSE127979_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_RNaseH_GSE127979_pos.bw K562_DRIPc_RNaseH_GSE127979_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_GSE127979_rep1_neg.bw K562_DRIPc_WT_GSE127979_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_GSE127979_rep1_pos.bw K562_DRIPc_WT_GSE127979_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_GSE127979_rep2_neg.bw K562_DRIPc_WT_GSE127979_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_GSE127979_rep2_pos.bw K562_DRIPc_WT_GSE127979_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_LS42B_neg.bw K562_DRIPc_WT_LS42B_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_LS42B_pos.bw K562_DRIPc_WT_LS42B_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_LS60A_rep1_neg.bw K562_DRIPc_WT_LS60A_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_LS60A_rep1_pos.bw K562_DRIPc_WT_LS60A_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_LS60B_rep2_neg.bw K562_DRIPc_WT_LS60B_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/K562_DRIPc_WT_LS60B_rep2_pos.bw K562_DRIPc_WT_LS60B_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_DRIP_WT_LS15A_rep1.bw NT2_DRIP_WT_LS15A_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_DRIP_WT_LS15B_rep2.bw NT2_DRIP_WT_LS15B_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_DRIPc_WT_SX011C_rep1_neg.bw NT2_DRIPc_WT_SX011C_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_DRIPc_WT_SX011C_rep1_pos.bw NT2_DRIPc_WT_SX011C_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_DRIPc_WT_SX011D_rep2_neg.bw NT2_DRIPc_WT_SX011D_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_DRIPc_WT_SX011D_rep2_pos.bw NT2_DRIPc_WT_SX011D_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_RNaseH_LS78D_neg.bw NT2_sDRIP_RNaseH_LS78D_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_RNaseH_LS78D_pos.bw NT2_sDRIP_RNaseH_LS78D_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_LS78A_rep1_neg.bw NT2_sDRIP_WT_LS78A_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_LS78A_rep1_pos.bw NT2_sDRIP_WT_LS78A_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_LS78B_rep2_neg.bw NT2_sDRIP_WT_LS78B_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_LS78B_rep2_pos.bw NT2_sDRIP_WT_LS78B_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_NV1LS1_rep1_neg.bw NT2_sDRIP_WT_NV1LS1_rep1_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_NV1LS1_rep1_pos.bw NT2_sDRIP_WT_NV1LS1_rep1_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_NV1LS2_rep2_neg.bw NT2_sDRIP_WT_NV1LS2_rep2_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/NT2_sDRIP_WT_NV1LS2_rep2_pos.bw NT2_sDRIP_WT_NV1LS2_rep2_pos.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/TC32_DRIP_WT_GSE68847.bw TC32_DRIP_WT_GSE68847.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/U2OS_DRIP_4OHT_EMTAB6318.bw U2OS_DRIP_4OHT_EMTAB6318.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/U2OS_DRIP_RNaseH_GSE115957.bw U2OS_DRIP_RNaseH_GSE115957.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/U2OS_DRIP_RNaseH_GSE129907.bw U2OS_DRIP_RNaseH_GSE129907.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/U2OS_DRIP_WT_EMTAB6318.bw U2OS_DRIP_WT_EMTAB6318.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/U2OS_DRIP_WT_GSE115957_rep1.bw U2OS_DRIP_WT_GSE115957_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/U2OS_DRIP_WT_GSE115957_rep2.bw U2OS_DRIP_WT_GSE115957_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/U2OS_DRIP_WT_GSE129907.bw U2OS_DRIP_WT_GSE129907.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/hPSC_DRIP_RNaseH_WT_PRJNA474076_rep1.bw hPSC_DRIP_RNaseH_WT_PRJNA474076_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/hPSC_DRIP_RNaseH_WT_PRJNA474076_rep2.bw hPSC_DRIP_RNaseH_WT_PRJNA474076_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/hPSC_DRIP_WT_PRJNA474076_rep1.bw hPSC_DRIP_WT_PRJNA474076_rep1.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/hPSC_DRIP_WT_PRJNA474076_rep2.bw hPSC_DRIP_WT_PRJNA474076_rep2.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/reuploaded_GSM3681021_RRChIP_WKKD_neg.bw reuploaded_GSM3681021_RRChIP_WKKD_neg.bw_converted_to_bed.bed
~/share/usr/bin/bigWigToBedGraph ./bigwig_files/reuploaded_GSM3681021_RRChIP_WKKD_pos.bw reuploaded_GSM3681021_RRChIP_WKKD_pos.bw_converted_to_bed.bed
