~/share/usr/bin/bedtools unionbedg -i HeLa_RDIP_WT_GSE120371_rep1_pos.bw_converted_to_bed.bed HeLa_RDIP_WT_GSE120371_rep1_neg.bw_converted_to_bed.bed > HeLa_RDIP_WT_GSE120371_rep1_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i IMR90_RDIP_WT_GSE68953_neg.bw_converted_to_bed.bed IMR90_RDIP_WT_GSE68953_pos.bw_converted_to_bed.bed > IMR90_RDIP_WT_GSE68953_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_qDRIP_WT_rep1_neg.bw_converted_to_bed.bed HeLa_qDRIP_WT_rep1_pos.bw_converted_to_bed.bed > HeLa_qDRIP_WT_rep1_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_DRIPc_WT_LS61C_rep2_neg.bw_converted_to_bed.bed HeLa_DRIPc_WT_LS61C_rep2_pos.bw_converted_to_bed.bed > HeLa_DRIPc_WT_LS61C_rep2_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_qDRIP_WT_rep2_neg.bw_converted_to_bed.bed HeLa_qDRIP_WT_rep2_pos.bw_converted_to_bed.bed > HeLa_qDRIP_WT_rep2_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HEK293_RDIP_WT_GSE68953_neg.bw_converted_to_bed.bed HEK293_RDIP_WT_GSE68953_pos.bw_converted_to_bed.bed > HEK293_RDIP_WT_GSE68953_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_DRIPc_WT_LS61A_rep1_pos.bw_converted_to_bed.bed HeLa_DRIPc_WT_LS61A_rep1_neg.bw_converted_to_bed.bed > HeLa_DRIPc_WT_LS61A_rep1_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_qDRIP_WT_rep3_pos.bw_converted_to_bed.bed HeLa_qDRIP_WT_rep3_neg.bw_converted_to_bed.bed > HeLa_qDRIP_WT_rep3_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i K562_DRIPc_WT_LS42B_pos.bw_converted_to_bed.bed K562_DRIPc_WT_LS42B_neg.bw_converted_to_bed.bed > K562_DRIPc_WT_LS42B_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i K562_DRIPc_WT_LS60B_rep2_pos.bw_converted_to_bed.bed K562_DRIPc_WT_LS60B_rep2_neg.bw_converted_to_bed.bed > K562_DRIPc_WT_LS60B_rep2_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_RDIP_WT_GSE120371_rep2_pos.bw_converted_to_bed.bed HeLa_RDIP_WT_GSE120371_rep2_neg.bw_converted_to_bed.bed > HeLa_RDIP_WT_GSE120371_rep2_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i NT2_DRIPc_WT_SX011D_rep2_pos.bw_converted_to_bed.bed NT2_DRIPc_WT_SX011D_rep2_neg.bw_converted_to_bed.bed > NT2_DRIPc_WT_SX011D_rep2_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i K562_DRIPc_WT_LS60A_rep1_neg.bw_converted_to_bed.bed K562_DRIPc_WT_LS60A_rep1_pos.bw_converted_to_bed.bed > K562_DRIPc_WT_LS60A_rep1_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i K562_DRIPc_WT_GSE127979_rep2_neg.bw_converted_to_bed.bed K562_DRIPc_WT_GSE127979_rep2_pos.bw_converted_to_bed.bed > K562_DRIPc_WT_GSE127979_rep2_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_qDRIP_WT_rep4_pos.bw_converted_to_bed.bed HeLa_qDRIP_WT_rep4_neg.bw_converted_to_bed.bed > HeLa_qDRIP_WT_rep4_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i NT2_DRIPc_WT_SX011C_rep1_pos.bw_converted_to_bed.bed NT2_DRIPc_WT_SX011C_rep1_neg.bw_converted_to_bed.bed > NT2_DRIPc_WT_SX011C_rep1_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i HeLa_DRIPc_WT_LS61H_rep3_neg.bw_converted_to_bed.bed HeLa_DRIPc_WT_LS61H_rep3_pos.bw_converted_to_bed.bed > HeLa_DRIPc_WT_LS61H_rep3_merged_strands.bed
~/share/usr/bin/bedtools unionbedg -i K562_DRIPc_WT_GSE127979_rep1_pos.bw_converted_to_bed.bed K562_DRIPc_WT_GSE127979_rep1_neg.bw_converted_to_bed.bed > K562_DRIPc_WT_GSE127979_rep1_merged_strands.bed
